### ISSUE TITLE
PhoCal dataset instruction

### ISSUE THREAD

**Issue by KSonPham** [DaoyiG/polarimetric-pose-prediction#1]
Hi Daoyi,

Would it be possible for you to write detail instructions on how to run your model with the PhoCal dataset?

Best regards,
Pham

**Comment by skarapanahalli** [comment]
> Hi Daoyi,
> 
> Would it be possible for you to write detail instructions on how to run your model with the PhoCal dataset?
> 
> Best regards, Pham

Yes, It will help me too, Can you please provide instructions on how to use this on the PhoCAL dataset

**Comment by DaoyiG** [comment]
Hi,

PhoCal dataset was designed for category-level pose estimation tasks, so I think they follow the structure of this: https://github.com/hughw19/NOCS_CVPR2019. 

To run our method (which is an instance-level method), you need to prepare the object visible mask, normal, and nocs for each train/test CAD model. You could generate those using whatever renderer you prefer, e.g., Pyrender, Pytorch3D, etc.
